stages:
    - test
    - mirror
    - package
    - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  BERT_FUNCTESTS: "1"
  DOCKER_HOST: "tcp://docker:2375/"

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - .cache

lint:
    image: python:3
    stage: test
    script:
        - ./ci/run-tests.sh lint

py36:
    image: python:3.6
    services:
        - docker:dind
    stage: test
    script:
        - ./ci/run-tests.sh py36

pypy3.6-7:
    image: pypy:3.6-7
    services:
        - docker:dind
    stage: test
    script:
        - ./ci/run-tests.sh pypy3

py37:
    image: python:3.7
    services:
        - docker:dind
    stage: test
    script:
        - ./ci/run-tests.sh py37

mirror-github:
    image: docker.git.cornhooves.org/build-tools/git-mirror:latest
    stage: mirror
    script:
        - ssh-load-key
        - git-mirror
    variables:
        GIT_MIRROR_URL: git@github.com:rschoon/bert.git
    only:
        - master
        - tags

package-dist:
    image: python:3
    stage: package
    script:
        - ./ci/build-dist.sh
    artifacts:
        paths:
            - dist/
        expire_in: 1 year

package-docs:
    image: python:3
    stage: package
    script:
        - pip install ".[docs]"
        - ./ci/build-docs.sh
    artifacts:
        paths:
            - dist/
        expire_in: 1 year

publish-docs:
    image: docker.git.cornhooves.org/build-tools/aws:latest
    stage: publish
    script:
        - ./ci/publish-docs-s3.py --bucket bert-build-docs
    only:
        - master
        - tags

#upload:
#    image: docker.git.cornhooves.org/build-tools/python-pkg-tools:latest
#    stage: publish
#    script:
#        - gpg-load-key
#        - twine upload -s "$GPG_SIGNING_KEY_ID" dist/*
#    only:
#        - tags
