stages:
    - test
    - package
#    - upload

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache

lint:
    image: python:3
    stage: test
    script:
        - ./ci/run-tests.sh lint

py36:
    image: python:3.6
    stage: test
    script:
        - ./ci/run-tests.sh py36

py37:
    image: python:3.7
    stage: test
    script:
        - ./ci/run-tests.sh py37

package-dist:
    image: python:3
    stage: package
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        paths:
            - dist/
        expire_in: 2 years
    only:
        - master
        - tags

#upload:
#    image: docker.git.cornhooves.org/docker-apps/python-pkg-tools:latest
#    stage: upload
#    script:
#        - gpg-load-key
#        - twine upload -s "$GPG_SIGNING_KEY_ID" dist/*
#    only:
#        - tags
