

files:
  patch.diff: |
    --- a/example.txt	2019-07-28 17:56:15.623664788 -0600
    +++ b/example.txt	2019-07-30 17:57:15.623664788 -0600
    @@ -2,7 +2,7 @@
     2
     3
     4
    -5
    +5 hello
     6
     7
     8
 
src:
  from: debian:stable

  tasks:
    - add:
        src: input
        dest: /test
    - patch:
        src: "{{functest_temp_dir}}/patch.diff"
        strip-dir: 1
        chdir: "/test"
    - read-file:
        path: /test/example.txt
        var: data

asserts: |
  assert "3\n4\n5 hello\n6\n7" in result.vars["data"]


