
files:
  patch.diff: |
    --- a/example.txt
    +++ b/example.txt
    @@ -5,6 +5,7 @@
     5
     6
     7
    +7.5
     8
     9
     10
    @@ -25,6 +26,7 @@
     25
     26
     27
    +27.5
     28
     29
     30
    \ No newline at end of file

src:
  from: debian:stable

  tasks:
    - add:
        src: input
        dest: /test
    - patch:
        src: "{{functest_temp_dir}}/patch.diff"
        chdir: "/test"
    - read-file:
        path: /test/example.txt
        var: data

asserts: |
  assert "6\n7\n7.5\n8\n9\n" in result.vars["data"]
  assert "26\n27\n27.5\n28\n29" in result.vars["data"]
