
files:
  patch.diff: |
    --- a/example.txt
    +++ b/example.txt
    @@ -4,8 +4,10 @@
     4
     5
     6
    +6.5
     7
     8
    +8.5
     9
     10
     11

src:
  from: debian:stable

  tasks:
    - add:
        src: input
        dest: /test
    - patch:
        src: "{{functest_temp_dir}}/patch.diff"
        chdir: "/test"
    - read-file:
        path: /test/example.txt
        var: data

asserts: |
  assert "5\n6\n6.5\n7\n8\n8.5\n9\n" in result.vars["data"]
