
temp-dir: yes

src:
  configs:
    - name: centos7
      from: centos:7
    - name: centos8
      from: centos:8

  stages:
    build:
      tasks:
        - script:
            contents: |
              #!/bin/bash
              mkdir /opt/hello
              echo 'hello world' > /opt/hello/world.txt
        - export-rpm:
            name: hellos
            version: 1.1
            release: '0.{{config.name}}'
            paths:
              - /opt/hello
            dest-dir: "{{functest_temp_dir}}"

    test:
      tasks:
        - add:
            src: "{{functest_temp_dir}}/hellos-1.1-0.{{config.name}}.noarch.rpm"
            dest: /tmp/
        - run: "rpm -i /tmp/hellos-1.1-0.{{config.name}}.noarch.rpm"

asserts: |
  pass
