
temp-dir: yes

src:
  from: debian:stable

  tasks:
    - script: 
        contents: |
          #!/bin/bash
          echo "hellos worlds" > /tmp/hello
    - export-file:
        paths:
          - glob: h*
            at: /tmp/
        dest: "{{functest_temp_dir}}/"

asserts: |
  import os

  with open(os.path.join(functest_temp_dir, "hello")) as f:
    assert f.read() == "hellos worlds\n"
