
temp-dir: yes

src:
  from: debian:stable

  tasks:
    - script: 
        contents: |
          #!/bin/bash
          mkdir /tmp/hello
          echo "hellos worlds" > /tmp/hello/data
    - export-tar:
        paths:
          - /tmp/hello
        dest: "{{functest_temp_dir}}/tar.gz"

asserts: |
  import os
  import tarfile

  with tarfile.open(os.path.join(functest_temp_dir, "tar.gz")) as t:
    while True:
      ti = t.next()
      if ti is None:
        break
      if ti.name == "/tmp/hello":
        assert t.extractfile(ti) is None
      elif ti.name == "/tmp/hello/data":
        assert t.extractfile(ti).read() == b"hellos worlds\n"
